# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on:
  schedule:
    - cron:  '0 14 * * *'
  push:
    branches:
      - master

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      
    - name: Use Node.js 12
      uses: actions/setup-node@v1
      with:
        version: 12

    - name: Set environment variables
      uses: allenevans/set-env@v1.0.0
      with:
        DISTRIBUTOR_HOST: ${{ secrets.DISTRIBUTOR_HOST }}
        DISTRIBUTOR_ID: ${{ secrets.DISTRIBUTOR_ID }}
        CAMPAIGN_LOGIN_PAGE: ${{ secrets.CAMPAIGN_LOGIN_PAGE }}
        EMAIL: ${{ secrets.EMAIL }}
        PASSWORD: ${{ secrets.PASSWORD }}
        CAMPAIGN_LIST_PAGE: ${{ secrets.CAMPAIGN_LIST_PAGE }}
        FBASE_API_KEY: ${{ secrets.FBASE_API_KEY }}
        FBASE_AUTH_DOMAIN: ${{ secrets.FBASE_AUTH_DOMAIN }}
        FBASE_DATABASE_URL: ${{ secrets.FBASE_DATABASE_URL }}
        FBASE_PROJECT_ID: ${{ secrets.FBASE_PROJECT_ID }}biorekredyt-pl
        FBASE_STORAGE_BUCKET: ${{ secrets.FBASE_STORAGE_BUCKET }}
        FBASE_MESSAGING_SENDER_ID: ${{ secrets.FBASE_MESSAGING_SENDER_ID }}
        FBASE_APP_ID: ${{ secrets.FBASE_APP_ID }}
        FBASE_MEASUREMENT_ID: ${{ secrets.FBASE_MEASUREMENT_ID }}
        
    - name: npm install and generate
      run: |
        npm install
        npm run generate
